name: "Demo: Terraform Apply"

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - "*.tfvars"
      - "*.json"
      - ".github/workflows/*.yml"

env:
  AWS_REGION: YOUR_AWS_REGION # e.g., us-west-2
  TERRAFORM_STATE_BUCKET: YOUR_TERRAFORM_STATE_BUCKET # e.g., terraform-state-123456789012-us-west-2

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    name: "Demo: Apply Changes"
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/YOUR_GITHUB_ACTIONS_ROLE
          role-session-name: GitHub-Actions-Terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.7.0

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan -var-file=terraform.tfvars
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}

      - name: Create Demo Summary
        if: always()
        run: |
          echo "# 🧪 StepSecurity Terraform Demo - Apply Results" >> $GITHUB_STEP_SUMMARY
          echo "## Status: ${{ steps.apply.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "## Changes Applied to StepSecurity:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`terraform" >> $GITHUB_STEP_SUMMARY
          terraform show -no-color tfplan | head -30 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "**Demo Repository**: Testing StepSecurity provider via GitHub Actions" >> $GITHUB_STEP_SUMMARY
