terraform {
  required_version = ">= 1.0"
  required_providers {
    stepsecurity = {
      source  = "step-security/stepsecurity"
      version = "~> 0.0.9"
    }
  }
}

provider "stepsecurity" {
  # api_key and customer will be read from environment variables:
  # STEP_SECURITY_API_KEY and STEP_SECURITY_CUSTOMER
}

# Create GitHub PR template configuration for your organization
resource "stepsecurity_github_pr_template" "example" {
  owner          = "organization-name"
  title          = "[StepSecurity] Apply security best practices"
  summary        = <<-EOT
    ## Summary

    This pull request has been generated by [StepSecurity](https://app.stepsecurity.io/github/organization-name/dashboard) as part of your enterprise subscription to ensure compliance with recommended security best practices. Please review and merge the pull request to apply these security enhancements.

    ## Security Fixes

    {{STEPSECURITY_SECURITY_FIXES}}

    ## Feedback
    For bug reports, feature requests, and general feedback; please create an issue in [step-security/secure-repo](https://github.com/step-security/secure-repo) or contact us via [our website](https://www.stepsecurity.io/).
  EOT
  commit_message = <<-EOT
    [StepSecurity] Apply security best practices

    Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
  EOT
  labels         = ["security", "automated"]
}
